### ISSUE TITLE
Linux - Steam Dirt Rally 1: Is not detecting right tilt?

### ISSUE THREAD

**Issue by KHZ-INTL** [rmst/yoke#12]
System information:
OS: Arch Linux x86_64
Kernel 4.18...-arch1-1-Arch
Game: Dirt Rally 1 - Steam edition, native support - non wine...

Issue:
The game does not detect tilting to the right, when setting key binds using keyboard and mouse profile, however, left tiling is detected. Can not test in joystick profile as the game uses "Y" axis of joystick to scroll up/down options. As result, the game scrolls up/down really fast. 

What I have tried:
"jtest-gtk" was able to detect the joystick, all axis were calibrated and indicated they were functional. Also tried to remap axis but unsuccessful, did not help. I had the steam client and game client up-to-date and restarted the PC one. 

Feature Request:
It would be handy to pause the inputs from the joystick without disconnecting it so that it would be possible to set keybindings. This would prevent the game from scrolling down/up options. However, I do not think this would resolve my problem. 

Please let me know if you need further information. Thanks in advance.

**Comment by rmst** [comment]
Yoke behaves like a standard linux joystick / gamepad. The gamepad tool (linked the readme) should help remap the axes for all SDL2-based games (which I believe includes Dirt Rally). It's a bit awkward to use but  you probably can do it if you research a bit online. I'm closing this because it's not really a problem with Yoke but with the game / gamepad-tool. If you manage to get it working let us know :)
