### ISSUE TITLE
Connectivity issues with Yoke over Wifi

### ISSUE THREAD

**Issue by rmst** [rmst/yoke#18]
Has anyone else experienced disconnects when using yoke via Wifi? To get good connectivity? I usually use USB tethering and connect manually, which seemed to be the only way for yoke to work reliably. Perhaps it would be sensible to get rid of the UDP over IP communication and instead use direct USB (and potentially bluetooth).

**Comment by pzmarzly** [comment]
I used Yoke only for about an hour, but it seemed reliable over Wifi. It probably depends on the router.

**Comment by pzmarzly** [comment]
Is this issue still relevant after the latest protocol changes?

**Comment by medape** [comment]
Probably not. I never had any real problems with the old one, and `events.py` hasn't thrown any malformed message error since the protocol change. I reckon it'll be less relevant when we get around to implementing a binary protocol.

(By the way, when we do, we should use more bits for the axes events. Yoke expects integers in [1, 32768] and jstest-gtk always reports within [-32767, 32767]; any 15-bit or 16-bit range would be a better match than the 8-bit values we're using now, at no cost of speed.)

**Comment by pzmarzly** [comment]
> By the way, when we do, we should use more bits for the axes events. Yoke expects integers in [1, 32768] and jstest-gtk always reports within [-32767, 32767]; any 15-bit or 16-bit range would be a better match than the 8-bit values we're using now, at no cost of speed

While I think that 1 byte of precision is enough for almost all cases (I'm not aware of any program that expects more precise input from a real gamepad/joystick/racing wheel), I'm not against increasing it either. If you want to, go ahead and increase it.

That's unrelated to this issue, though, so I'm going to close it now.
