### ISSUE TITLE
Cannot upgrade gamepads

### ISSUE THREAD

**Issue by edomato** [rmst/yoke#48]
When I connect to the server running on my laptop (Debian) with the new Android app and when I go to "Upgrade gamepad" it says:

Cleartext HTTP traffic to ip-of-my-laptop no permitted.

The Android version is 9.

Let me know if you need any other information.

Greets.
Ernesto

**Comment by pzmarzly** [comment]
I received an email about this error few weeks ago, the user there was using Android 10.

Apparently in some update (security patch level? webview update?) Google disabled cleartext traffic for apps, even for local networks. I'm not sure how browsers are affected, it may be worth investigating.

My reply to that email was:

> so Google broke Yoke again?
> 
> Basically the last time the problem was that they removed some APIs from webviews served over HTTP. So we moved to webviews served from local filesystem (`file://` schema), and we fetch files over HTTP from Java code. https://github.com/rmst/yoke/issues/39
> 
> I personally have moved away from Android, to jailbroken iOS, so I'm afraid I won't be much of a help.
> 
> We didn't want anyone trying to tweak the layout to have to have Android toolchain installed (hardcoding layout files into APK), or to upload their layouts to the cloud, or to transfer files over USB and select the folder with new layout every time (Storage Access Framework). [But it may be necessary after all. I think we could also utilize Github Gists for syncing.]
> 
> Maybe someone could hack together file transfers over UDP? Or FTP? That could buy us some time.

**Comment by pzmarzly** [comment]
Okay, apparently we had a fix ready for that, but I forgot about it. Sorry, my bad https://github.com/rmst/yoke-android/pull/9

**Comment by edomato** [comment]
Ok, perfect.

How can I test it?, cause that issue points to the Android source code and I don't have the resources right now to compile de apk from source at this moment.

Is the F-Droid version updated with that fix?, or is the apk on the server repository updated with that fix?.

If I can test it, we could close this issue if that fix the problem.

Thanks a lot.

**Comment by pzmarzly** [comment]
In the past the APK was build by either @rmst or @medape . This is my first time building an APK, and I'm not sure whether hitting "Build" in Android Studio is enough now (from what I recall, it wasn't enough back in 2014, when I last compiled an Android apk - back then you also had to configure signing). Since I'm using an iPhone now, could you check whether the APK below works? I had to zip it due to GitHub file extension limitation. If it is fine, I will push it to this repo.

[app-debug.apk.zip](https://github.com/rmst/yoke/files/4741890/app-debug.apk.zip)

For future reference, the steps I did:
- download Android Studio 4.0 from Jetbrains Toolbox
- open Tools->SDK Manager
- install Android 9 SDK from "SDK platforms"
- on "SDK Tools" check "Show Package Details", and install Build-Tools v28.0.3
- reload Android Studio and build the app
- grab the output: `yoke-android/app/build/outputs/apk/debug/app-debug.apk`
